name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run basic check
        run: |
          echo "Hello from CI!"
          # (Later: replace this with lint/tests)
